# Site settings
title: Anna L. Ziff
email: aziff@tamu.edu
description: > # this means to ignore newlines until "baseurl:" 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://aziff.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  aziff
google_scholar_id: CHOnVB4AAAAJ
orcid_id: 0000-0001-6403-8516
stackoverflow_id: 17389222/vadulrashkov

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "Assistant Professor"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
