# Site settings
title: Anna L. Ziff
email: anna.ziff@duke.edu
description: > # this means to ignore newlines until "baseurl:"
  Anna L. Ziff, Ph.D. Candidate in the Economics Department of Duke University
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://aziff.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  aziff

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "Ph.D. Candidate"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""