
title: <a href="/index.html">Anna Ziff</a>
description: Economics Ph.D. Student at <a href="https://econ.duke.edu/">Duke University</a>
google_analytics: UA-170340094-1
theme: jekyll-theme-dinky
github_comments_repository: "aziff/aziff.github.io"